[package]
name = "proxy_http"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
common = { path = "../common" }
httparse.workspace = true
mux = { path = "../mux" }
tokio.workspace = true
tracing.workspace = true
url.workspace = true
